# Contexte

Transports Canada élabore et applique des politiques et des règlements pour faire progresser la sécurité et la sûreté du système de transport maritime du Canada. Le Ministère favorise un réseau efficace et durable qui protège l’environnement maritime et contribue au développement économique.

En novembre 2016, le gouvernement du Canada a annoncé le Plan national de protection des océans (PPO) au montant de 1,5 milliard de dollars ayant pour objectif d’améliorer la sécurité maritime et la navigation responsable, de protéger le milieu marin canadien et d’offrir de nouvelles possibilités pour les Canadiens.

Grâce à ce plan, le gouvernement du Canada est résolu à conserver et à restaurer les écosystèmes marins côtiers qui sont vulnérables à l’augmentation du trafic maritime, tout en réduisant l’incidence du trafic maritime quotidien. De nombreuses préoccupations ont été exprimées concernant l’augmentation du transport maritime et l’impact des autres activités maritimes (un secteur d’activités pouvant être une source importante d’impacts anthropiques) sur les écosystèmes côtiers et maritimes ainsi que sur le mode de vie des communautés autochtones.

Afin de faciliter une meilleure coordination, Transports Canada et le gouvernement du Québec, dans le cadre du Plan d’action Saint-Laurent , ont joint leurs efforts visant le développement et l’application d’un cadre commun d’évaluation des effets cumulatifs des activités maritimes actuelles et futures sur le Saint-Laurent et le Saguenay tout en encourageant une étroite collaboration avec les Premières Nations, les intervenants maritimes et les collectivités côtières.

Transports Canada collabore avec les communautés autochtones, les intervenants de l’industrie maritime et les collectivités côtières depuis 2017 et continuera à organiser des ateliers collaboratifs pour faire en sorte que toutes les parties soient impliquées de manière égale tout au long du projet.
