# Mandat

Transports Canada a engagé une équipe de l’Université Laval pour développer une méthodologie d’analyse et effectuer l’évaluation des effets cumulatifs des activités maritimes dans le Saint-Laurent (tronçon fluvial et estuaire) et la rivière Saguenay (partie en eau profonde) au Québec.

Ce projet appuiera Transports Canada et le gouvernement du Québec dans la conception d’un cadre commun d’évaluation des effets cumulatifs des activités maritimes; et permettra d’identifier des outils et des stratégies d’atténuation pouvant s’appliquer aux déplacements actuels de navires et au développement de projets futurs. Le tout sera effectué de façon collaborative afin d’assurer la coordination entre les Premières Nations, les scientifiques et les organismes de réglementation et de prendre des décisions fondées sur des éléments probants.

## Description des besoins

L’équipe de l’Université Laval développera une méthodologie d’analyse des effets cumulatifs des activités maritimes qui sera présentée aux différents collaborateurs. En utilisant cette méthodologie, l’équipe de l’Université Laval effectuera l’évaluation des effets cumulatifs des activités maritimes sur les composantes valorisées identifiées par les Premières Nations et diverses parties prenantes pour le Saint-Laurent (tronçon fluvial et estuaire) et la rivière Saguenay (partie en eau profonde) au Québec.

À partir de cette évaluation, l’équipe de l’Université Laval produira un rapport résumant la méthodologie employée, l’analyse effectuée, les résultats et les conclusions qui seront présentés aux différents collaborateurs.

L’équipe de l’Université Laval participera aux ateliers de travail et discussion avec les Premières Nations, les intervenants maritimes et les collectivités côtières afin de bien intégrer les commentaires et l’apport de chacun.

## Portée

L’équipe de l’Université Laval fournira une évaluation intégrée des impacts cumulatifs des activités maritimes sur les écosystèmes du Saint-Laurent (tronçon fluvial et estuaire, i.e. de Montréal à Pointe-des-Monts) et du Saguenay (partie en eau profonde jusqu’à Saint-Fulgence), caractérisera la structure spatiale de certaines composantes valorisées ciblées du Saint-Laurent et du Saguenay, évaluera la vulnérabilité de ces composantes à de multiples facteurs de stress (dont la source est liée aux activités maritimes), et évaluera les impacts cumulatifs à partir de la cartographie des facteurs de stress et des composantes valorisées. Cette étude favorisera une évolution vers une manière plus proactive et holistique de gérer les écosystèmes marin et dulcicole.

La collaboration avec les Premières Nations et l’intégration du savoir autochtone est une exigence. L’équipe de l’Université Laval devra, entre autres, se baser sur les discussions et conclusions des ateliers de travail avec les représentants des Premières Nations et autres parties prenantes pour l’élaboration du projet. Les savoirs autochtones, lorsque disponibles, seront utilisés afin de détecter les changements dans le milieu et pour améliorer notre compréhension des effets cumulatifs.

## Développement de la méthodologie

La méthode d’analyse utilisée devra être en mesure :

- d’intégrer les connaissances autochtones et traditionnelles recueillies;
- d’utiliser différents types de données, notamment les données géo-spatiales et tabulaires (non géo-référencées);
- d’étudier des limites spatiales et temporales variables;
- de caractériser des sources de stress environnementaux multiples;
- d’évaluer de façon intégrée les répercussions sur diverses composantes valorisées (identifiées lors des ateliers de travail), notamment les composantes biologiques, environnementales, culturelles et socioéconomiques.
