# Mandat

## Titre du projet

Évaluation des effets cumulatifs des activités maritimes sur le Saint-Laurent ainsi que la rivière Saguenay

## Objectif

Transports Canada requiert les services d’un entrepreneur pour développer une méthodologie d’analyse et effectuer l’évaluation des effets cumulatifs des activités maritimes dans le Saint-Laurent (tronçon fluvial et estuaire) et la rivière Saguenay (partie en eau profonde) au Québec.

Ce projet appuiera Transports Canada et le gouvernement du Québec dans la conception d’un cadre commun d’évaluation des effets cumulatifs des activités maritimes; et permettra d’identifier des outils et des stratégies d’atténuation pouvant s’appliquer aux déplacements actuels de navires et au développement de projets futurs. Le tout sera effectué de façon collaborative afin d’assurer la coordination entre les Premières Nations, les scientifiques et les organismes de réglementation et de prendre des décisions fondées sur des éléments probants.

## Description des besoins

L`entrepreneur doit développer une méthodologie d’analyse des effets cumulatifs des activités maritimes qui sera présentée aux différents collaborateurs.
En utilisant cette méthodologie, l’entrepreneur doit effectuer l’évaluation des effets cumulatifs des activités maritimes sur les composantes valorisées identifiées par les Premières Nations et diverses parties prenantes pour le Saint-Laurent (tronçon fluvial et estuaire) et la rivière Saguenay (partie en eau profonde) au Québec.

À partir de cette évaluation, l’entrepreneur doit produire un rapport résumant la méthodologie employée, l’analyse effectuée, les résultats et les conclusions qui seront présentés aux différents collaborateurs.

L`entrepreneur doit aussi participer aux ateliers de travail et discussion avec les Premières Nations, les intervenants maritimes et les collectivités côtières afin de bien intégrer les commentaires et l’apport de chacun.

## Portée

L’entrepreneur doit fournir une évaluation intégrée des impacts cumulatifs des activités maritimes sur les écosystèmes du Saint-Laurent (tronçon fluvial et estuaire, i.e. de Montréal à Pointe-des-Monts) et du Saguenay (partie en eau profonde jusqu’à Saint-Fulgence), être en mesure de caractériser la structure spatiale de certaines composantes valorisées ciblées du Saint-Laurent et du Saguenay, évaluer la vulnérabilité de ces composantes à de multiples facteurs de stress (dont la source est liée aux activités maritimes), et évaluer les impacts cumulatifs à partir de la cartographie des facteurs de stress et des composantes valorisées. Cette étude favorisera une évolution vers une manière plus proactive et holistique de gérer les écosystèmes marin et dulcicole.

La collaboration avec les Premières Nations et l’intégration du savoir autochtone est une exigence. L’entrepreneur doit, entre autres, se baser sur les discussions et conclusions des ateliers de travail avec les représentants des Premières Nations et autres parties prenantes pour l’élaboration du projet. Les savoirs autochtones, lorsque disponibles, devront être considérés dans les données qui aideront à détecter les changements dans le milieu et à améliorer notre compréhension des effets cumulatifs.

## Tâches et services détaillés

L’entrepreneur doit accomplir les tâches et activités suivantes :

### Lancement du projet, planification du travail et réunions d’avancement

Une réunion de lancement en personne sera organisée dans les deux (2) semaines suivant l’attribution du contrat (début février). L’objectif de la réunion consiste, au moins, à présenter l’équipe de l’entrepreneur et à discuter du plan de travail et de l’approche proposée, de l’affectation des ressources et du calendrier de l’entrepreneur. L’échéancier de remise du premier rapport d’étape (voir ci-après) sera déterminé durant la réunion de lancement. L’entrepreneur doit soumettre un plan de travail préliminaire aux fins d’approbation par le chargé de projet durant la semaine suivant la réunion de lancement.

De plus, l’entrepreneur doit prévoir des réunions/téléconférences mensuelles avec le chargé de projet pour faire le point sur le projet et/ou fournir les résultats préliminaires. Ceci peut inclure :

- un résumé des dernières activités réalisées;
- ce qui a été effectué et ce qui était prévu, mais qui n’a pas été réalisé;
- ce qui est prévu jusqu’à la prochaine réunion;

Les questions, les problèmes et les avertissements devront être signalés au chargé de projet à mesure qu’ils surviennent.

### Participation aux ateliers/webinaires de travail

La participation à divers ateliers de travail avec les collaborateurs et partenaires est un prérequis. L’entrepreneur doit se baser sur les discussions et conclusions de ces ateliers pour l’élaboration du projet.

Le premier atelier se tiendra le 11 février 2020 et permettra de bien identifier la portée de l’évaluation, i.e. les composantes valorisées et les facteurs de stress (des composantes potentielles sont la qualité de l’eau, les habitats de reproduction des poissons, espèces en péril, activités traditionnelles telles que la pêche aux mollusques). La portée couverte par l’analyse de l’entrepreneur sera consolidée avec Transports Canada, le gouvernement du Québec et les autres partenaires et collaborateurs avant la fin février 2020.

Lors d’un webinaire au début avril 2020, l’entrepreneur doit présenter l’approche suggérée pour l’évaluation afin d’obtenir l’approbation du chargé de projet et des collaborateurs. L’entrepreneur doit remettre à Transports Canada le document présentant l’aperçu de la méthode d’évaluation à la mi-mars 2020 afin que les participants puissent examiner les documents avant de participer aux discussions.

Dans un atelier prévu en mars 2021, l’entrepreneur doit présenter les constatations préliminaires de l’évaluation à des fins de discussion avant de produire le rapport final. L’entrepreneur doit remettre à Transports Canada le rapport préliminaire trois (3) semaines avant l’atelier afin que les participants puissent examiner les documents avant de participer aux discussions.

La présentation du rapport final lors d’un atelier doit se faire au début du mois de février 2022. L’entrepreneur doit remettre à Transports Canada le rapport avant le 31 décembre 2021.


### Développement de la méthodologie

La méthode d’analyse utilisée doit être en mesure :

- d’intégrer les connaissances autochtones et traditionnelles recueillies par Transports Canada auprès des communautés autochtones;
- d’utiliser différents types de données, notamment les données géo-spatiales et tabulaires (non géo-référencées);
- d’étudier des limites spatiales et temporales variables;
- de caractériser des sources de stress environnementaux multiples;
- d’évaluer de façon intégrée les répercussions sur diverses composantes valorisées (identifiées lors des ateliers de travail), notamment les composantes biologiques, environnementales, culturelles et socioéconomiques. Les répercussions positives potentielles des activités maritimes (p. ex. : réduction des émissions de gaz à effet de serre et répercussions socio-économiques positives) doivent aussi pouvoir être prises en considération.

### Évaluation des effets cumulatifs

Cette évaluation doit inclure une caractérisation de la structure spatiale des composantes valorisées (portrait de l’aire d’étude), l’état de vulnérabilité des composantes à de multiples facteurs de stress découlant des activités maritimes , et l’analyse des impacts cumulatifs à partir de la cartographie des facteurs de stress (incluant leurs sources) et des composantes valorisées.

L’étendue de l’analyse est déterminée par les éléments suivants :

- la définition des facteurs de stress clés des activités maritimes pouvant influencer des composantes valorisées potentielles dans le secteur visé (effectué lors des ateliers de travail de novembre 2017 et juin 2018);
- la sélection de limites spatiales et temporelles appropriées dans le site visé (effectué en collaboration avec les partenaires en 2018);
- la détermination de liens entre les facteurs de stress décelés des activités maritimes et les composantes valorisées sélectionnées (supporté par un exercice du Secrétariat canadien de consultation scientifique effectué en novembre 2019);

La collecte et le regroupement de données actuelles sur les activités maritimes régionales, les données environnementales, culturelles et traditionnelles seront effectués en collaboration avec les diverses parties prenantes.

Les données recueillies pour effectuer l’analyse doivent être conservées dans une base de données qui sera éventuellement utilisé pour le partage d’information sur le Saint-Laurent et le Saguenay avec les diverses parties prenantes.

Une discussion doit avoir lieu avec l’entrepreneur pour échanger sur la meilleure façon de communiquer au public l'information recueillie dans le cadre de cette évaluation.

### Rapport préliminaire

L’entrepreneur doit préparer une ébauche du rapport comprenant les constatations préliminaires. Celui-ci doit être remis à Transports Canada pour questions et commentaires trois (3) semaines avant l’atelier du mois de mars 2021.

### Rapport final

L’entrepreneur doit intégrer les commentaires reçus lors de l’atelier sur le rapport d‘évaluation provisoire et fournir un rapport final avant le 31 décembre 2021.

### Calendrier des livrables

| Description ou « livrable » | Échéance |
| :-------------------------- | :------- |
| Lancement et préparation du calendrier et du plan de travail | Deux (2) semaines suivant l’attribution du contrat (début février 2020)
| Document présentant un aperçu de la méthode d’évaluation des impacts cumulés et de l'approche de collecte et de gestion des données | Mi-mars 2020 |
| Présentation du document méthodologique aux partenaires et collaborateurs pour commentaires et approbation par webinaire | Avril 2020 |
| Rapport sommaire et présentation des constatations préliminaires aux fins de commentaires lors d’un atelier | Mars 2021 |
| Livraison du rapport final aux fins de traduction et de diffusion | Le ou avant le 31 décembre 2021 |
| Présentation du rapport final lors d’un atelier | Début février 2022|

Le chargé de projet examinera chaque produit livrable et indiquera l’approbation et l’acceptation ou la nécessité pour l’entrepreneur d’apporter des révisions.

En plus de fournir les livrables prévus, l’entrepreneur est chargé des activités suivantes : s’assurer que les travaux sont planifiés adéquatement, qu’ils sont organisés et effectués par du personnel expérimenté et compétent; au besoin, organiser les réunions qui s’imposent; fournir son propre soutien administratif et logistique.

### Format des livrables

L’entrepreneur fournira les documents suivants en français par courriel au chargé de projet :

- des versions électroniques du rapport préliminaire et du rapport final en format Microsoft Word et en format PDF;
- la liste complète et la documentation/bibliographie ainsi que les sources de données;
- les ensembles de données, les modèles/tableurs ainsi que la méthodologie qui ont été conçus pour appuyer l’analyse, y compris les explications et les références;
- les bases de données devront être livrées dans un format facilitant l’accès par Transports Canada; elles devront contenir la définition des champs ainsi que la description des données.
- un format qui permet d’optimiser l’accès et le partage des connaissances/données à de multiples organismes.

### Soutien fourni par le Canada

Le chargé de projet de Transports Canada fournira à l'entrepreneur tous les documents de référence nécessaires et pertinents et sera disponible pour répondre aux questions tout au long du projet, au besoin. Il contribuera à la collecte de données qui aideront à détecter les changements dans le milieu et à améliorer notre compréhension des effets cumulatifs.

### Réunions, ateliers et déplcaements

L’entrepreneur doit participer aux téléconférences qui se tiendront une fois par mois avec le chargé de projet de Transports Canada. Il peut également être invité à participer, en personne ou par conférence téléphonique, aux réunions interministérielles (approximativement 2), qui se tiendront en général dans la ville de Québec.

Dans le cadre de ce contrat, l’entrepreneur doit être présent en personne à trois (3) ateliers qui se tiendront dans les villes de Québec ou Montréal.
