# Équipe de travail

Philippe Archambault agira à titre de gestionnaire de projet. Détenteur d’un doctorat en biologie (1998), il a d’abord été chercheur à Pêches et Océans Canada (2000-2007) puis professeur à l’Institut des sciences de la mer de l’Université du Québec à Rimouski (2007-2017). Depuis 2017, il est professeur à l’Université Laval. Alliant recherche fondamentale et théorique, Philippe étudie les effets de perturbations diverses (d’origine naturelle et anthropique) sur les écosystèmes depuis plus de 20 ans. Il a co-dirigé ou participé à de nombreux programmes de recherche axés sur la biodiversité benthique autant au niveau canadien qu’à l’international. Les résultats de ses travaux ont été utilisés, entre autres, pour le développement d’aires marines protégées et il est l’auteur/coauteur de > 120 articles scientifiques revus par les pairs. Il possède les compétences linguistiques orales, de compréhension et écrites à des niveaux de français et d’anglais avancés. Il supervise une équipe de > 25 personnes, incluant des étudiants gradués et des professionnels de recherche. Dans le cadre de ce projet, Philippe Archambault endossera le rôle de gestionnaire de projet. Il sera conséquemment responsable de la supervision du projet et aura la responsabilité du respect des échéanciers et de la production des livrables.

David Beauchesne est le post-doctorant pressenti pour la réalisation de ce projet. Fort de son expérience développée en cours de doctorat, David a toutes les qualifications requises pour mener à bien les travaux sur les effets cumulatifs des activités maritimes. Il possède les compétences linguistiques orales, de compréhension et écrites à des niveaux de français et d’anglais avancés.

Un étudiant de premier cycle universitaire pourrait prendre part à ce projet en tant qu’auxiliaire de recherche. Cet auxiliaire de recherche pourrait être embauché à temps complet pendant l’été, ou encore à temps partiel en cours d’année scolaire. Le candidat sera choisi suite à un affichage conforme aux procédures de l’Université Laval et devra détenir de l’expérience en système d’information géographique et en programmation.
